version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apw
      POSTGRES_DB: db

    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/posgressql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  db:
